.TH HankSmash "12 May 2014" "Version 0.87"
.SH NAME
HankSmash - baby-safe computer input learning and fun
.SH SYNOPSIS
.B HankSmash
[\fIOPTIONS\fR]
.SH OPTIONS
.TP
\fB\-u\fR, \fB\-\-uppercase\fR
Whether to show UPPER-CASE letters.
.TP
\fB\-\-sound_blacklist\fR=\fIGLOB\fR
List sound filenames which should not be used in HankSmash.
.sp
Use this option to disable certain especially annoying sound effects. The sound effects filenames can be located in /path/to/HankSmash/data/sounds.
.SH DESCRIPTION
.PP
HankSmash is based on bambam, a kyeboard and mouse game for babies written in Python.
HankSmash aims to introduce infants to computers by giving them the opportunity to interact with them.
The screen is cleared at random.
.SH NOTES
\fBTo quit, type the word "quit" in the game\fR.
To mute, "mute" and to unumte, "unmute".
Pressing letter keys prints them in random locations and colours.
Pressing any other key produces images from /data/pics in random locations.
Click and dragging draws in randomly changing colours.
.SH AUTHOR
P. H. Madore <henrypaulmadore@gmail.com> phmadore.com
.PP
with code by 
.sp
Spike Burch <spikeb@gmail.com> and 
.sp
Marcin Owsiany <marcin@owsiany.pl>
.sp
.SH RELEASE
HankSmash is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.PP
HankSmash is owned and maintained by Grand Royal Industries, an unregistered DBA in Grand Junction, Colorado, USA. Up-to-date copies, support, and so forth can be found at apps.grandroyalindustries.com.
